//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBookMobile
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string mobile { get; set; }
        public System.DateTime createDate { get; set; }
        public string name { get; set; }
        public string company { get; set; }
        public bool haveRecommended { get; set; }
        public Nullable<long> tguid { get; set; }
        public byte[] timestamp { get; set; }
        public bool isAttention { get; set; }
        public Nullable<System.DateTime> attentionDate { get; set; }
    }
}
