//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedProjRecord
    {
        public long id { get; set; }
        public long fid { get; set; }
        public long oldProjId { get; set; }
        public long newProjId { get; set; }
        public System.DateTime created { get; set; }
        public long @operator { get; set; }
    }
}
