//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttentionStatistics
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int attentionCount { get; set; }
        public int todayAttentionCount { get; set; }
        public int attentionUserCount { get; set; }
        public int todayAttentionUserCount { get; set; }
        public int invitationCount { get; set; }
        public int todayInvitationCount { get; set; }
        public decimal successRate { get; set; }
    }
}
