//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockedStatistics
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int dockedTotalNum { get; set; }
        public int todayDockedNum { get; set; }
        public int todaySuccessfulDockedNum { get; set; }
        public int agreedDockedTotalNum { get; set; }
        public int todayAgreedDockedNum { get; set; }
        public int todayRejectedDockedNum { get; set; }
    }
}
