//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DockedRecord
    {
        public long rid { get; set; }
        public long fid { get; set; }
        public long sender { get; set; }
        public long receiver { get; set; }
        public Tgnet.FootChat.Docked.DockedStatus status { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public string message { get; set; }
    }
}
