//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootPrintImg
    {
        public long id { get; set; }
        public long fid { get; set; }
        public string imageKey { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string address { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> photoTime { get; set; }
        public bool isEnabled { get; set; }
        public Nullable<int> order { get; set; }
        public bool isComfirm { get; set; }
        public Nullable<System.DateTime> comfirmDate { get; set; }
        public Nullable<long> comfirmer { get; set; }
    }
}
