//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootPrintStatistics
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int totalCount { get; set; }
        public int todayPassFootPrintCount { get; set; }
        public int todayUnPassFootPrintCount { get; set; }
        public int creatorCount { get; set; }
        public int todayCreatorCount { get; set; }
        public int fpViewCount { get; set; }
        public int totalViewUserCount { get; set; }
        public int gt2FollowProjNum { get; set; }
        public int gt2FollowUserNum { get; set; }
        public int totalPassFootPrintCount { get; set; }
    }
}
