//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootUser
    {
        public long uid { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string areaNo { get; set; }
        public Nullable<Tgnet.FootChat.User.UserSex> sex { get; set; }
        public string company { get; set; }
        public string job { get; set; }
        public Tgnet.FootChat.User.VerifyStatus verifyStatus { get; set; }
        public Nullable<System.DateTime> verifyDate { get; set; }
        public Nullable<long> verifyUser { get; set; }
        public string verifyFailReason { get; set; }
        public Nullable<System.DateTime> submiVerifytDate { get; set; }
        public string verifyImage { get; set; }
        public bool isInner { get; set; }
        public System.DateTime lastLogin { get; set; }
        public int loginCount { get; set; }
        public bool isLocked { get; set; }
        public string lockReason { get; set; }
        public System.DateTime created { get; set; }
        public string userFacePah { get; set; }
        public string userFacePathSmall { get; set; }
        public Nullable<System.DateTime> lockDate { get; set; }
        public Nullable<long> lockOperator { get; set; }
        public bool isNeedVerify { get; set; }
        public string cover { get; set; }
        public bool isVerifiedLocked { get; set; }
        public Nullable<System.DateTime> verifiedlockDate { get; set; }
    }
}
