//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InteractionStatistics
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int callTotalNum { get; set; }
        public int todayCallTotalNum { get; set; }
        public int callUserNum { get; set; }
        public int vipCallTotalNum { get; set; }
        public int vipTodayCallTotalNum { get; set; }
        public int vipCallUserNum { get; set; }
        public int todayVipCallUserNum { get; set; }
    }
}
