//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileInfo
    {
        public long uid { get; set; }
        public string deviceId { get; set; }
        public string resolution { get; set; }
        public string os { get; set; }
        public string trademark { get; set; }
        public System.DateTime updated { get; set; }
        public string ip { get; set; }
        public string clientVersion { get; set; }
    }
}
