//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public long sender { get; set; }
        public long receiver { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public Tgnet.FootChat.Relation.RelationType rType { get; set; }
        public bool inReceiverBlack { get; set; }
        public bool inSenderBlack { get; set; }
        public bool isStar { get; set; }
        public string remark { get; set; }
        public string description { get; set; }
        public byte from { get; set; }
        public long dateVersion { get; set; }
        public bool isNotNotiry { get; set; }
        public bool inSession { get; set; }
        public string message { get; set; }
        public bool sessionTop { get; set; }
    }
}
