//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long uid { get; set; }
        public string name { get; set; }
        public Nullable<Tgnet.FootChat.User.UserSex> sex { get; set; }
        public string weChat { get; set; }
        public string products { get; set; }
        public string company { get; set; }
        public string job { get; set; }
        public string bussinessAreas { get; set; }
        public Nullable<int> yearOfWorking { get; set; }
        public string stageNos { get; set; }
        public string needCustomSource { get; set; }
        public string needCooperateProduct { get; set; }
        public Nullable<double> lastYearAchievement { get; set; }
        public Nullable<double> thisYearGoal { get; set; }
        public string necessaryDoType { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public bool isBuy { get; set; }
        public Nullable<System.DateTime> buyDate { get; set; }
    }
}
