//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserServiceStateUpdateRecord
    {
        public long rid { get; set; }
        public long uid { get; set; }
        public Tgnet.FootChat.User.ServiceRecordType type { get; set; }
        public System.DateTime creted { get; set; }
        public int IncreaseDays { get; set; }
        public string remark { get; set; }
    }
}
