//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tgnet.FootChat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStatistics
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public int totalCount { get; set; }
        public int todayCreatedCount { get; set; }
        public int verifiedCount { get; set; }
        public int todayPassCount { get; set; }
        public int todayUnPassCount { get; set; }
        public int trailUserCount { get; set; }
        public int officialUserCount { get; set; }
        public int todayPaidUserCount { get; set; }
        public decimal paidRate { get; set; }
    }
}
